### ISSUE TITLE
critical information leaked

### ISSUE THREAD

**Issue by hektor-7** [MhL5/forkify-js-app#1]
hey

> [!WARNING]
> your code contains the API key

and also for some reason when i try to open the project, this happens:
![image](https://github.com/MhL5/forkify-js-app/assets/136856523/7ccd3d7e-b46d-4d50-8b84-e148b0a3ab61)

**Comment by MhL5** [comment]
tnx i will look into it
edit

**Comment by MhL5** [comment]
closed
